### ISSUE TITLE
YAML and JSON are failing with error: “Unexpected error running Liquibase: Could not find databaseChangeLog node” 

### ISSUE THREAD

**Issue by szandany** [liquibase/liquibase-snowflake#34]
When trying to run and "update" or "status" YAML and JSON changeLogs, the command will fail with the following error:
“Unexpected error running Liquibase: Could not find databaseChangeLog node”

STR:

1. Include the liquibase-snowflake-4.1.1.jar extension and snowflake-jdbc-3.9.2.jar driver in the ${liquibase home}/lib directory.
2. Make sure you are running Liquibase Version: 4.1.1
3. Create a YAML or JSON changeLog.
For example:
YAML chagneLog

```
changeSet:  
  id:  createTable-example  
  author:  liquibase-docs  
  changes:  
  -  createTable:  
      catalogName:  cat  
      columns:  
      -  column:  
          name:  address2 
          type:  varchar(255)  
      remarks:  A String  
      tableName:  person
```

JSON changeLog

```
{
    "changeSet":{
       "id":"createTable-example",
       "author":"liquibase-docs",
       "changes":[
          {
             "createTable":{
                "columns":[
                   {
                      "column":{
                         "name":"address",
                         "type":"varchar(255)"
                      }
                   }
                ],
                "tableName":"person",
                "remarks":"A String"
             }
          }
       ]
    }
 }
```

Run `liquibase update`

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-843) by [Unito](https://www.unito.io/learn-more)
